# Generated by Django 3.1.2 on 2021-03-06 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrangWeb',
            fields=[
                ('ten_trang_web', models.CharField(db_index=True, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('the_vung_tin_tuc', models.CharField(max_length=300)),
                ('thu_tu_cua_the_vung_tin_tuc', models.IntegerField(default=0)),
                ('the_tieu_de', models.CharField(max_length=300)),
                ('thu_tu_cua_the_tieu_de', models.IntegerField(default=0)),
                ('the_tac_gia', models.CharField(max_length=300)),
                ('thu_tu_cua_the_tac_gia', models.IntegerField(default=0)),
                ('ngay_them', models.DateTimeField(default='07-03-2021 04:14:43')),
                ('trang_thai_chay', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='top50',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_bai_bao', models.CharField(db_index=True, max_length=300, unique=True)),
                ('tieu_de', models.CharField(max_length=300)),
                ('tac_gia', models.CharField(max_length=300)),
                ('ngay_them', models.DateTimeField()),
                ('noi_dung', models.TextField()),
                ('chu_de', models.TextField()),
                ('tu_khoa', models.TextField()),
                ('ten_trang_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trangWeb.trangweb')),
            ],
        ),
        migrations.CreateModel(
            name='BaiBao',
            fields=[
                ('link_bai_bao', models.CharField(db_index=True, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('tieu_de', models.CharField(max_length=300)),
                ('tac_gia', models.CharField(max_length=300)),
                ('ngay_them', models.DateTimeField()),
                ('noi_dung', models.TextField()),
                ('chu_de', models.TextField()),
                ('tu_khoa', models.TextField()),
                ('ten_trang_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trangWeb.trangweb')),
            ],
        ),
    ]
