# Generated by Django 3.1.7 on 2021-04-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='so_bai_tung_trang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_web', models.CharField(max_length=300)),
                ('so_bai_viet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tong_bai_hang_ngay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_bai_viet', models.IntegerField()),
                ('ngay_them', models.DateTimeField(default='14-04-2021 16:07:38')),
            ],
        ),
        migrations.CreateModel(
            name='TrangWeb',
            fields=[
                ('link_trang_web', models.CharField(db_index=True, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('the_vung_tin_tuc', models.CharField(max_length=300)),
                ('thu_tu_cua_the_vung_tin_tuc', models.IntegerField(default=0)),
                ('the_tieu_de', models.CharField(max_length=300)),
                ('thu_tu_cua_the_tieu_de', models.IntegerField(default=0)),
                ('the_noi_dung', models.CharField(max_length=300)),
                ('thu_tu_the_noi_dung', models.IntegerField(default=0)),
                ('ngay_them', models.DateTimeField(default='14-04-2021 16:07:38')),
                ('trang_thai_chay', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='top50',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_bai_bao', models.CharField(db_index=True, max_length=300, unique=True)),
                ('tieu_de', models.CharField(max_length=300)),
                ('tac_gia', models.CharField(max_length=300)),
                ('ngay_them', models.DateTimeField()),
                ('noi_dung', models.TextField()),
                ('chu_de', models.TextField()),
                ('tu_khoa', models.TextField()),
                ('ten_trang_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trangWeb.trangweb')),
            ],
        ),
        migrations.CreateModel(
            name='BaiBao',
            fields=[
                ('link_bai_bao', models.CharField(db_index=True, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('tieu_de', models.CharField(max_length=300)),
                ('tac_gia', models.CharField(max_length=300)),
                ('ngay_them', models.DateTimeField()),
                ('noi_dung', models.TextField()),
                ('chu_de', models.TextField()),
                ('tu_khoa', models.TextField()),
                ('ten_trang_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trangWeb.trangweb')),
            ],
        ),
    ]
