# Generated by Django 3.1.2 on 2021-03-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='so_bai_tung_trang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_web', models.CharField(max_length=300)),
                ('so_bai_viet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tong_bai_hang_ngay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_bai_viet', models.IntegerField()),
                ('ngay_them', models.DateTimeField(default='07-03-2021 21:12:24')),
            ],
        ),
        migrations.AlterField(
            model_name='trangweb',
            name='ngay_them',
            field=models.DateTimeField(default='07-03-2021 21:12:24'),
        ),
    ]
