# Generated by Django 3.1.7 on 2021-04-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baibao',
            name='ngay_them',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='so_bai_tung_trang',
            name='so_bai_viet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tong_bai_hang_ngay',
            name='ngay_them',
            field=models.DateTimeField(default='17-04-2021'),
        ),
        migrations.AlterField(
            model_name='trangweb',
            name='ngay_them',
            field=models.DateTimeField(default='17-04-2021 01:43:18'),
        ),
    ]
