# Generated by Django 3.1.7 on 2021-04-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangWeb', '0002_auto_20210307_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trangweb',
            old_name='ten_trang_web',
            new_name='link_trang_web',
        ),
        migrations.AlterField(
            model_name='tong_bai_hang_ngay',
            name='ngay_them',
            field=models.DateTimeField(default='01-04-2021 23:57:39'),
        ),
        migrations.AlterField(
            model_name='trangweb',
            name='ngay_them',
            field=models.DateTimeField(default='01-04-2021 23:57:39'),
        ),
    ]
