# Generated by Django 3.1.7 on 2021-04-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangWeb', '0003_auto_20210401_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trangweb',
            old_name='the_tac_gia',
            new_name='the_noi_dung',
        ),
        migrations.RenameField(
            model_name='trangweb',
            old_name='thu_tu_cua_the_tac_gia',
            new_name='thu_tu_the_noi_dung',
        ),
        migrations.AlterField(
            model_name='tong_bai_hang_ngay',
            name='ngay_them',
            field=models.DateTimeField(default='02-04-2021 00:02:52'),
        ),
        migrations.AlterField(
            model_name='trangweb',
            name='ngay_them',
            field=models.DateTimeField(default='02-04-2021 00:02:52'),
        ),
    ]
