# Generated by Django 3.1.7 on 2021-04-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangWeb', '0003_auto_20210417_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='tu_khoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_khoa', models.CharField(max_length=300)),
                ('so_lan', models.IntegerField()),
                ('ngay_them', models.DateTimeField(default='2021-04-21')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('password', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('permission', models.CharField(max_length=300)),
                ('ngay_them', models.DateTimeField(default='2021-04-21')),
            ],
        ),
        migrations.AlterField(
            model_name='tong_bai_hang_ngay',
            name='ngay_them',
            field=models.DateTimeField(default='2021-04-21'),
        ),
        migrations.AlterField(
            model_name='trangweb',
            name='ngay_them',
            field=models.DateTimeField(default='21-04-2021 14:33:15'),
        ),
    ]
