# Generated by Django 3.1.7 on 2021-04-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangWeb', '0004_auto_20210402_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tong_bai_hang_ngay',
            name='ngay_them',
            field=models.DateTimeField(default='04-04-2021 14:02:44'),
        ),
        migrations.AlterField(
            model_name='trangweb',
            name='ngay_them',
            field=models.DateTimeField(default='04-04-2021 14:02:44'),
        ),
    ]
